### ISSUE TITLE
Crash on Android with 2022.3.22f1

### ISSUE THREAD

**Issue by cihadturhan** [GameAnalytics/GA-SDK-UNITY#34]
After upgrading IAP package, it somehow caused GameAnalytics to crash. Here is the call stack:
```
2024/07/12 02:27:03.482 10137 11387 Warn System.err 	at java.lang.Class.classForName(Native Method)
2024/07/12 02:27:03.482 10137 11387 Warn System.err 	at java.lang.Class.forName(Class.java:454)
2024/07/12 02:27:03.482 10137 11387 Warn System.err 	at java.lang.Class.forName(Class.java:379)
2024/07/12 02:27:03.482 10137 11387 Warn System.err 	at com.gameanalytics.sdk.utilities.Reflection.invokeStaticMethod(Reflection.java:64)
2024/07/12 02:27:03.482 10137 11387 Warn System.err 	at com.gameanalytics.sdk.utilities.Reflection.getAdvertisingInfoObject(Reflection.java:16)
2024/07/12 02:27:03.482 10137 11387 Warn System.err 	at com.gameanalytics.sdk.utilities.Reflection.getAdId(Reflection.java:23)
2024/07/12 02:27:03.482 10137 11387 Warn System.err 	at com.gameanalytics.sdk.utilities.GAUtilities.getOAID(GAUtilities.java:254)
2024/07/12 02:27:03.482 10137 11387 Warn System.err 	at com.gameanalytics.sdk.device.GADevice.getOAID(GADevice.java:272)
2024/07/12 02:27:03.482 10137 11387 Warn System.err 	at com.gameanalytics.sdk.state.GAState.getIdentifier(GAState.java:1529)
2024/07/12 02:27:03.483 10137 11387 Warn System.err 	at com.gameanalytics.sdk.state.GAState.getInitAnnotations(GAState.java:1469)
2024/07/12 02:27:03.483 10137 11387 Warn System.err 	at com.gameanalytics.sdk.http.GAHTTPApi.requestInitReturningDict(GAHTTPApi.java:231)
2024/07/12 02:27:03.483 10137 11387 Warn System.err 	at com.gameanalytics.sdk.state.GAState.startNewSession(GAState.java:902)
2024/07/12 02:27:03.483 10137 11387 Warn System.err 	at com.gameanalytics.sdk.state.GAState.internalInitialize(GAState.java:1744)
2024/07/12 02:27:03.484 10137 11387 Warn System.err 	at com.gameanalytics.sdk.GameAnalytics$15.execute(GameAnalytics.java:461)
2024/07/12 02:27:03.484 10137 11387 Warn System.err 	at com.gameanalytics.sdk.threading.GAThreading$1.run(GAThreading.java:32)
2024/07/12 02:27:03.484 10137 11387 Warn System.err 	at java.util.TimerThread.mainLoop(Timer.java:562)
2024/07/12 02:27:03.484 10137 11387 Warn System.err 	at java.util.TimerThread.run(Timer.java:512)
```

I'm going to upgrade GA to 7.8 to 7.10.0-beta just to see if it fixes my issue.
I'll close if it fixes it.

**Comment by cihadturhan** [comment]
Ok it's fixed

**Comment by MehdiMashmool** [comment]
> Ok it's fixed

Which version of IAP you are using?
I have the same issue but after upgrading to GA 7.10.0-beta, the issue not fixed.

**Comment by cihadturhan-st** [comment]
> > Ok it's fixed
> 
> Which version of IAP you are using? I have the same issue but after upgrading to GA 7.10.0-beta, the issue not fixed.

I don’t recall but I used the latest update as Google play shows billing library warning.

**Comment by Gogoshika-ga** [comment]
Same handled exception as #35, silenced in the Android SDK shipped with 8.2.0. Closing.
