### ISSUE TITLE
java.lang.ClassNotFoundException: com.huawei.hms.ads.identifier.AdvertisingIdClient

### ISSUE THREAD

**Issue by dhamelin** [GameAnalytics/GA-SDK-UNITY#35]
I'm seeing this exception on Android. While using SDK 7.9.1

07-18 16:56:24.727 14411 14723 W System.err: java.lang.ClassNotFoundException: com.huawei.hms.ads.identifier.AdvertisingIdClient
07-18 16:56:24.727 14411 14723 W System.err: 	at java.lang.Class.classForName(Native Method)
07-18 16:56:24.727 14411 14723 W System.err: 	at java.lang.Class.forName(Class.java:536)
07-18 16:56:24.727 14411 14723 W System.err: 	at java.lang.Class.forName(Class.java:467)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.utilities.Reflection.invokeStaticMethod(Reflection.java:64)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.utilities.Reflection.getAdvertisingInfoObject(Reflection.java:16)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.utilities.Reflection.getAdId(Reflection.java:23)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.utilities.GAUtilities.getOAID(GAUtilities.java:254)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.device.GADevice.getOAID(GADevice.java:273)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.state.GAState.getIdentifier(GAState.java:1529)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.state.GAState.ensurePersistedStates(GAState.java:425)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.state.GAState.internalInitialize(GAState.java:1734)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.GameAnalytics$15.execute(GameAnalytics.java:462)
07-18 16:56:24.727 14411 14723 W System.err: 	at com.gameanalytics.sdk.threading.GAThreading$1.run(GAThreading.java:32)
07-18 16:56:24.727 14411 14723 W System.err: 	at java.util.TimerThread.mainLoop(Timer.java:563)
07-18 16:56:24.727 14411 14723 W System.err: 	at java.util.TimerThread.run(Timer.java:513)
07-18 16:56:24.727 14411 14723 W System.err: Caused by: java.lang.ClassNotFoundException: com.huawei.hms.ads.identifier.AdvertisingIdClient

**Comment by MehdiMashmool** [comment]
I have the same issue

**Comment by cihadturhan** [comment]
Any updates on how to get rid of this warning? I hate seeing it on the logcat

**Comment by Gogoshika-ga** [comment]
The Android SDK no longer prints this handled exception. 8.2.0 ships that version. Closing.
